<?php
namespace ITEC\Presencial\DAW\DatosArrayElementos;
class ArrayElementos{
       public static array $ATTRIBUTES = [
        "accept" => ["form", "input"],
        "accept-charset" => ["form"],
        "accesskey" => "global",
        "action" => ["form"],
        "align" => ["applet", "caption", "col", "colgroup", "hr", "iframe", "img", "table", "tbody", "td", "tfoot", "tr"],
        "alt" => ["applet", "area", "img", "input"],
        "async" => ["script"],
        "autocomplete" => ["form", "input"],
        "autofocus" => ["button", "input", "keygen", "select", "textarea"],
        "autoplay" => ["audio", "video"],
        "autosave" => ["input"],
        "bgcolor" => ["body", "col", "colgroup", "marquee", "table", "tbody", "tfoot", "td", "th", "tr"],
        "border" => ["img", "object", "table"],
        "buffered" => ["audio", "video"],
        "challenge" => ["keygen"],
        "charset" => ["meta", "script"],
        "checked" => ["command", "input"],
        "cite" => ["blockquote", "del", "ins", "q"],
        "class" => "global",
        "code" => ["applet"],
        "codebase" => ["applet"],
        "color" => ["basefont", "font", "hr"],
        "cols" => ["textarea"],
        "colspan" => ["td", "th"],
        "content" => ["meta"],
        "contenteditable" => "global",
        "contextmenu" => "global",
        "controls" => ["audio", "video"],
        "coords" => ["area"],
        "data" => ["object"],
        "data-*" => "global",
        "datetime" => ["del", "ins", "time"],
        "default" => ["track"],
        "defer" => ["script"],
        "dir" => "global",
        "dirname" => ["input", "textarea"],
        "disabled" => ["button", "command", "fieldset", "input", "keygen", "optgroup", "option", "select", "textarea"],
        "download" => ["a", "area"],
        "draggable" => "global",
        "dropzone" => "global",
        "enctype" => ["form"],
        "for" => ["label", "output"],
        "form" => ["button", "fieldset", "input", "keygen", "label", "meter", "object", "output", "progress", "select", "textarea"],
        "formaction" => ["input", "button"],
        "headers" => ["td", "th"],
        "height" => ["canvas", "embed", "iframe", "img", "input", "object", "video"],
        "hidden" => "global",
        "high" => ["meter"],
        "href" => ["a", "area", "base", "link"],
        "hreflang" => ["a", "area", "link"],
        "http-equiv" => ["meta"],
        "icon" => ["command"],
        "id" => "global",
        "ismap" => ["img"],
        "itemprop" => "global",
        "keytype" => ["keygen"],
        "kind" => ["track"],
        "label" => ["track"],
        "lang" => "global",
        "language" => ["script"],
        "list" => ["input"],
        "loop" => ["audio", "bgsound", "marquee", "video"],
        "low" => ["meter"],
        "manifest" => ["html"],
        "max" => ["input", "meter", "progress"],
        "maxlength" => ["input", "textarea"],
        "media" => ["a", "area", "link", "source", "style"],
        "method" => ["form"],
        "min" => ["input", "meter"],
        "multiple" => ["input", "select"],
        "muted" => ["video"],
        "name" => ["button", "form", "fieldset", "iframe", "input", "keygen", "object", "output", "select", "textarea", "map", "meta", "param"],
        "novalidate" => ["form"],
        "open" => ["details"],
        "optimum" => ["meter"],
        "pattern" => ["input"],
        "ping" => ["a", "area"],
        "placeholder" => ["input", "textarea"],
        "poster" => ["video"],
        "preload" => ["audio", "video"],
        "pubdate" => ["time"],
        "radiogroup" => ["command"],
        "readonly" => ["input", "textarea"],
        "rel" => ["a", "area", "link"],
        "required" => ["input", "select", "textarea"],
        "reversed" => ["ol"],
        "rows" => ["textarea"],
        "rowspan" => ["td", "th"],
        "sandbox" => ["iframe"],
        "scope" => ["th"],
        "scoped" => ["style"],
        "seamless" => ["iframe"],
        "selected" => ["option"],
        "shape" => ["a", "area"],
        "size" => ["input", "select"],
        "sizes" => ["link", "img", "source"],
        "span" => ["col", "colgroup"],
        "spellcheck" => "global",
        "src" => ["audio", "embed", "iframe", "img", "input", "script", "source", "track", "video"],
        "srcdoc" => ["iframe"],
        "srclang" => ["track"],
        "srcset" => ["img"],
        "start" => ["ol"],
        "step" => ["input"],
        "style" => "global",
        "summary" => ["table"],
        "tabindex" => "global",
        "target" => ["a", "area", "base", "form"],
        "title" => "global",
        "type" => ["button", "input", "command", "embed", "object", "script", "source", "style", "menu"],
        "usemap" => ["img", "input", "object"],
        "value" => ["button", "option", "input", "li", "meter", "progress", "param"],
        "width" => ["canvas", "embed", "iframe", "img", "input", "object", "video"],
        "wrap" => ["textarea"]
    ];
    public static array $AttributesEmpty = [
        "area",
        "base",
        "br",
        "col",
        "colgroup",
        "command",
        "embed",
        "hr",
        "img",
        "input",
        "keygen",
        "link",
        "meta",
        "param",
        "source",
        "track",
        "wbr"
    ];
}
?>